apiVersion: v1
kind: Service
metadata: 
  name: demo
  namespace: demo
  labels: 

spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app/name: app
    app/instance: blue
    app/version: "1.10"
  type: NodePort
