apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-green
  namespace: demo
  labels:
    app/name: app
    app/instance: green
    app/version: "{{ .Values.green.image.tag }}"
spec:
  replicas: {{ .Values.green.replicaCount }}
  selector:
    matchLabels:
      app/name: app
      app/instance: green
  template:
    metadata:
      labels:
        app/name: app
        app/instance: green
        app/version: "{{ .Values.green.image.tag }}"
    spec:
      containers: 
        - name: nginx
          image: "nginx:{{ .Values.green.image.tag }}"
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 1
          volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html/
      volumes:
        - name: html
          configMap:
            name: content-green
